baseURL = 'https://bb.learningnow.com.au/'
languageCode = 'en-us'
title = 'Brainbreak'
theme = 'lugo'

[params]
  favicon = "/favicon.ico"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
