Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "bb.learningnow.local"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Forward ports
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  
  # Disable automatic VirtualBox Guest Additions update
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  
  # Run Ansible provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible-playbook.yml"
    ansible.groups = {
      "brainbreak" => ["default"]
    }
    # Let Vagrant handle the SSH connection details
    ansible.host_key_checking = false
    ansible.verbose = "v"
  end
end